### ISSUE TITLE
Either problem

### ISSUE THREAD

**Issue by chrismurrph** [lihaoyi/fastparse#32]
Please try running this two ways.
1. target = numberFirst
2. target = textFirst

The output should be the same for both but it is not.
1. numberFirst:
    ><
2. textFirst:
    >Some text<  

```scala
object BugReport extends App {
  object MyParser {
    val number = P(CharPred( (ch:Char) => {ch.isDigit || ch == '.'}).rep.! )
    val text = P(CharPred( (ch:Char) => {ch.isSpaceChar || ch.isLetterOrDigit}).rep.! )
    val textFirst = (text | number).!
    val numberFirst = (number | text).!
    def target = numberFirst
    def parseItem(str: String) = target.parse(str)
  }

  val input = "Some text"
  MyParser.parseItem(input) match {
    case Result.Success(res, _) =>
      println(">" + res + "<")
    case x => println("Could not parse the input string:" + x)
  }
}
```

**Comment by lihaoyi** [comment]
Your problem is that you're using `.rep`, which accepts 0 repetitions as valid input. Thus your `number` and `text` parsers are always succeeding, you never use the right-hand-side of the `|` operators, and it's succeeding before it finishes parsing the whole string. To fix this

- If you want at least 1 repetition, use `.rep(1)`. This is probably what you want
- use `~ End` at the end of your parser to make sure it fails if it can't parse everything
- Ask future questions on the gitter channel rather than issues; these aren't issues =P

**Comment by chrismurrph** [comment]
Thanks for the support. Done one and two and will do three.
Robert C Martin in one of his books advises more methods and less method arguments. Translated to here that could mean `.rep0` and `.rep1` become methods, `rep(Int)` gets no default arguments and lastly that you get less support correspondence.
