### ISSUE TITLE
CharIn whitespace problem

### ISSUE THREAD

**Issue by ihji** [lihaoyi/fastparse#57]
I found that overriding `WhitespaceApi` also affects `CharIn`'s behavior. Is this a bug?

```scala
import fastparse.WhitespaceApi
import fastparse.noApi._

val White = WhitespaceApi.Wrapper{
  import fastparse.all._
  NoTrace(" ".rep)
}
import White._

val x = P("abc" ~ CharIn("def").rep.!)
x.parse("abcdd d")

// result: res0: fastparse.core.Result[String] = Success(dd d,7)
```

**Comment by ihji** [comment]
`repX` can solve this problem. I found it while I read the source code. Thanks!

**Comment by lihaoyi** [comment]
Yeah, would be nice to document it =D This is more to do with `.rep` than with `CharIn`, since anything with `.rep` will exhibit this behavior.

FWIW, `CharIn("def").rep` could also be rewritten as `CharsWhile("def".contains(_))`, which is equivalent but a lot faster and doesn't suffer the effects of `.rep`
